### ISSUE TITLE
Snapshot files in the same directory as test files

### ISSUE THREAD

**Issue by tomatau** [asvetliakov/typescript-snapshots-plugin#10]
Hello,

I'm using a VSCode plugin that seems to be obsolete and referring to this instead, so I'm hoping the fix is the same.

I'm using a library called `chai-jest-snapshot` and my snapshot files are in the same directory as my test files:

```
├── App
    ├── App.js
    ├── App.spec.js
    └── App.spec.js.snap
```

This is giving me errors `Corresponding snapshot doesn't exist` and `The snapshot is redunant`.

Test name and snapshot name e.g.

```js
describe(`App Component`, function () {
    it(`renders a header as fifth child`
```

and

```js
exports[`App Component renders a header as fifth child 1`] = `
```

I've the following settings:

```json
{
  "snapshotTools.snapshotDir": "./",
  "snapshotTools.testFileDir": "./",
  "snapshotTools.testMethods": [
    "test",
    "it",
    "fit",
    "xit",
    "xtest",
    "it.only"
  ]
}
```

**Comment by asvetliakov** [comment]
Hello. Sorry for not responding earlier. Starting from v0.1.0 of ```snapshot-tools```, the extension bundles this plugin so it will work for both JS/TS without need of manual plugin installation. See [this page](https://github.com/asvetliakov/typescript-snapshots-plugin/tree/master/vscode).

Your issue also must be supported now, add to your ```jsconfig.json``` following:
```json
{
    "compilerOptions": {
        "plugins": [
            {
                "name": "typescript-snapshots-plugin",
                "snapshotDir": "./"
            }
        ],
    }
}
```

**Comment by tomatau** [comment]
Hello, thanks for the reply.

Let me confirm this.

So now instead of installing an editor plugin once for VSCode. I need to install a typescript related npm package as a dependency for every JS project I have and want this editor feature (which will be an npm dependency event for people who don't use my editor), or globally for every version of node I run on my machine? This seems a little backwards, what was wrong with the editor plugin?

**Comment by asvetliakov** [comment]
No. The editor plugin bundles TS plugin automatically and uses internal typescript version of VSCode. You don't need to install typescript if you're not using it.

You only need ```jsconfig.json``` file for your project (if you don't have it already) to specify ```snapshotDir``` setting if you need override plugin defaults (which uses jest conventions)

**Comment by tomatau** [comment]
Oh good! I tried this approach you've just said straight after seeing your initial reply! -- but it didn't seem to register any snapshot file syntax or enable any of the features!

OSX: Mojave
VSCode: Version 1.27.2
Snapshot-tools: 0.1.0

**Comment by asvetliakov** [comment]
Did you create/add ```jsonfig.json``` in project root with my snippet above? Try to restart TS server (by vscode command) or reload vscode to pick up the changes.

Also snapshot syntax is not included now - i'd recommend to install ```vscode-jest``` extension and disable it. For the old plugin i just copied the syntax from here

**Comment by tomatau** [comment]
Yes I created the jsconfig.json.

I didn't want to install vscode-jest as it seemed far too heavy for me, and I don't actually use jest... But I'll try installing it and disabling it.

How do I restart the TS server by vscode command? I've manually restarted vscode about 4 times trying to get it working - didn't help.

**Comment by asvetliakov** [comment]
can you provide any repro? This works for me:

![screen shot 2018-09-29 at 21 54 55](https://user-images.githubusercontent.com/8881674/46249968-6e230d80-c432-11e8-98a8-865e49e6b6c7.png)

**Comment by tomatau** [comment]
Sure, I'm working on a branch right now so the changes aren't applied.

https://github.com/tomatau/breko-hub/blob/master/src/app/components/App/App.spec.js#L93

I didn't realise you'd removed `"matchSnapshot"` as one of the defaults for `"snapshotCallIdentifiers"` so that has helped with the quick info.

However, the go to definition still doesn't work and the syntax highlights for quick info are broken too. Definitely had to have vscode-jest installed for the syntax.

Bit frustrating to have yet ANOTHER config file in my project root, I was using `.vscode/settings.json` for my vscode specific settings so far to keep them namespaced.

**Comment by asvetliakov** [comment]
Yes, go to definition is broken. However it works if there is a function definition for ```matchSnapshot```. Will fix it soon

**Comment by tomatau** [comment]
It's all good. This is mainly me venting a frustration with VSCode if anything. Maybe the jsconfig.json will grow to be a convention for more settings instead of being another diversion for configuration... wish they used the package.json instead  or at least have the same js specific capabilities in the settings.json :(

**Comment by asvetliakov** [comment]
@tomatau If you're using snapshots, why not using jest directly? The default settings are working with jest without any jsconfig/additional configuration.

**Comment by tomatau** [comment]
Yes the update fixed goto definition thanks! Quick info syntax highlighting is still broke though.

I'm not using jest because it slows my test suite down from under 1second to 20 seconds by starting up multiple processes, also the mess of configuration (https://jestjs.io/docs/en/configuration#defaults) in jest isn't appealing compared to my simple and effective mocha setup.

Chai-jest-snapshot is very effective for my requirements as well as being more lightweight and I have it integrated with subtrees in enzyme very nicely.

**Comment by asvetliakov** [comment]
0.1.2 brings back syntax snapshot syntax highlight. Please also vote for [This request](https://github.com/jest-community/vscode-jest/issues/385) in vscode-jest repo.
