### ISSUE TITLE
Can't preview snapshot from TypeScript file generated to JS

### ISSUE THREAD

**Issue by ktutnik** [asvetliakov/typescript-snapshots-plugin#11]
Thanks for making this tools, its really helpful.

But I unable to use it on my TypeScript project which generates JS. Im not using ts-jest so the snapshot generated was: `<my spec file>.js.snap` 
When I rename the snapshot file into `<my spec file>.ts.snap` it showing properly. Any workaround on this issue?

**Comment by asvetliakov** [comment]
Snapshot files must be ```original_filename.snap```. You're precompiling TS tests and running jest on JS files, right? This won't work. I'd recommend you to use ```@babel/typescript``` if you don't want to use ts-jest

**Comment by ktutnik** [comment]
Yes I'm running jest on the JS files.

Can this be supported in the future release?

**Comment by asvetliakov** [comment]
Sure
