### ISSUE TITLE
Issue on TypeScript 4.0.2 ?

### ISSUE THREAD

**Issue by ktutnik** [asvetliakov/typescript-snapshots-plugin#25]
Hi @asvetliakov 
I having problem using TypeScript snapshot when setting VSCode typescript to 4.0.2? 
![image](https://user-images.githubusercontent.com/1106884/92339793-56f2fd00-f0ea-11ea-9fcd-9642ed7e8fae.png)

Are there any workaround recently for this?

**Comment by asvetliakov** [comment]
Make sure you've switched to workspace version of typescript

**Comment by ktutnik** [comment]
yes, I use the workspace version, but it doesn't work
![image](https://user-images.githubusercontent.com/1106884/92347705-806c5280-f103-11ea-824d-da612d8ea494.png)

**Comment by ktutnik** [comment]
Look like the new update of VSCode 1.49.0 shipped with TypeScript 4.0.2 fixes this.
