### ISSUE TITLE
Feature: publish to VSCode extensions marketplace

### ISSUE THREAD

**Issue by dbkaplun** [asvetliakov/typescript-snapshots-plugin#3]
Thanks for considering!

**Comment by asvetliakov** [comment]
Hello @dbkaplun
Yes, i'm planning to bundle this TS plugin as VS Code plugin.
 
In meantime, you can check this VS Code plugin:
https://marketplace.visualstudio.com/items?itemName=asvetliakov.snapshot-tools

It was done before TS plugin and works slightly differently, but has same features.
