### ISSUE TITLE
syntax highlighting is a bit too aggressive

### ISSUE THREAD

**Issue by patrickhulce** [asvetliakov/typescript-snapshots-plugin#8]
Hey there great plugin, love it thanks for your work! 👏 👏 👏 

I'm running into an issue though where an HTML-like thing is saved in a snapshot and then the rest of the syntax highlighting gets messed up for the entire file. I'm not sure how it all works, but perhaps it'd be better to identify the string ranges first and *then* apply syntax highlighting if possible?

Example
![image](https://user-images.githubusercontent.com/2301202/41790596-ec814710-7607-11e8-8d6b-ee540160ccf1.png)

```
exports[`file should handle HTML-like stuff 1`] = `"<input id=\\"label-text-input\\" type=\\"text\\">"`;

exports[`file should handle HTML-like stuff 2`] = `now everything is ugly for the rest of the file :(`;

**Comment by asvetliakov** [comment]
Hello @patrickhulce 

The TS plugin does not do anything with syntax highlighting. Instead you should open the issue in [vscode-jest](https://github.com/jest-community/vscode-jest) repository or the one which provides the snapshot files colorization (i know only about vscode-jest)

**Comment by patrickhulce** [comment]
Hm interesting, I don't have vscode-jest installed and enabling/disabling your extension turns syntax highlighting on/off for .snap files. Maybe it's VSCode trying to do syntax highlighting on it's own once there's a language service?

**Comment by asvetliakov** [comment]
Ah, then looks like you're using [https://github.com/asvetliakov/snapshot-tools](snapshot-tools) 😄 . It has a same copy of vscode-jest syntax highlighting for snapshot files, so i'd recommend you to anyway fill the issue in vscode-jest. When it will be fixed, i just port it to snapshot-tools extension.

**Comment by patrickhulce** [comment]
Oh whoops, my bad! Clicked links too fast without reading sorry :) will do
